In [11]:
import pandas as pd
# Load the CSV file into a pandas DataFrame
data = pd.read_csv("H21/errorH21.csv", on_bad_lines='skip')

#Drop the first column
data = data.drop(data.columns[0], axis=1)

#Get unique data and their count
unique_values = data.stack().value_counts()

unique_values_df = unique_values.rename_axis('unique_value').reset_index(name='count')

# Display the grouped data as a table
unique_values_df.head(24)

                                         unique_value  count
0                         AssertionError('0 != 99')]]    283
1             IndexError('list index out of range')]]    257
2           IndexError('string index out of range')]]    230
3    AssertionError("'odde' != 'des'\n- odde\n+ de...    146
4    AssertionError("'des' != 'odde'\n- des\n+ odd...    145
5    TypeError("'>' not supported between instance...    108
6                       AssertionError('None != 0')]]    103
7    AttributeError("'int' object has no attribute...    103
8                         AssertionError('59 != 0')]]     85
9                          AssertionError('1 != 2')]]     80
10                      AssertionError('None != 1')]]     80
11                     AssertionError('None != []')]]     71
12          NameError("name 'vare' is not defined")]]     69
13                       AssertionError("'1' != 1")]]     62
14   TypeError("unsupported operand type(s) for -:...     52
15        TypeError("'int' object is not iterable")]]     42
16                      AssertionError("'0' != 99")]]     33
17   TypeError("'int' object is not subscriptable")]]     33
18   AssertionError("'odd' != 'odde'\n- odd\n+ odd...     33
19         AssertionError("'u' != 'a'\n- u\n+ a\n")]]     29
20                      AssertionError('None != 2')]]     28
21   TypeError('can only concatenate str (not "int...     26
22                 AssertionError("None != 'odde'")]]     25
23   TypeError("'<=' not supported between instanc...     24

In [12]:
# Load the CSV file into a pandas DataFrame
data = pd.read_csv("H21/errorH21.csv", on_bad_lines='skip')

#Drop the first column
data = data.drop(data.columns[0], axis=1)

#Get unique data and their count
unique_values = data.stack().value_counts()

# Filter unique values containing "NameError"
name_error_values = [value for value in unique_values.index if "NameError" in value]
name_error_counts = unique_values[name_error_values]

# Sum the counts of the NameError values
name_error_sum = name_error_counts.sum()

# Filter unique values containing "AssertionError"
assertion_error_values = [value for value in unique_values.index if "AssertionError" in value]
assertion_error_counts = unique_values[assertion_error_values]

# Sum the counts of the AssertionError values
assertion_error_sum = assertion_error_counts.sum()

#Filter unique values containing "TypeError"
type_error_values = [value for value in unique_values.index if "TypeError" in value]
type_error_counts = unique_values[type_error_values]

# Sum the counts of the TypeError values
type_error_sum = type_error_counts.sum()

#Filter unique values containing "IndexError"
index_error_values = [value for value in unique_values.index if "IndexError" in value]
index_error_counts = unique_values[index_error_values]

# Sum the counts of the IndexError values
index_error_sum = index_error_counts.sum()

#Filter unique values containing "AttributeError"
attribute_error_values = [value for value in unique_values.index if "AttributeError" in value]
attribute_error_counts = unique_values[attribute_error_values]

# Sum the counts of the AttributeError values
attribute_error_sum = attribute_error_counts.sum()

#Filter unique values containing "UnboundLocalError"
unbound_local_error_values = [value for value in unique_values.index if "UnboundLocalError" in value]
unbound_local_error_counts = unique_values[unbound_local_error_values]

# Sum the counts of the UnboundLocalError values
unbound_local_error_sum = unbound_local_error_counts.sum()

#Filter unique values containing "ValueError"
value_error_values = [value for value in unique_values.index if "ValueError" in value]
value_error_counts = unique_values[value_error_values]

# Sum the counts of the ValueError values
value_error_sum = value_error_counts.sum()

#Filter unique values containing "KeyError"
key_error_values = [value for value in unique_values.index if "KeyError" in value]
key_error_counts = unique_values[key_error_values]

# Sum the counts of the KeyError values
key_error_sum = key_error_counts.sum()

# Display the grouped data as a table
print("Sum of NameError: ", name_error_sum)
print("Sum of AssertionError: ", assertion_error_sum)
print("Sum of TypeError: ", type_error_sum)
print("Sum of IndexError: ", index_error_sum)
print("Sum of AttributeError: ", attribute_error_sum)
print("Sum of UnboundLocalError: ", unbound_local_error_sum)
print("Sum of ValueError: ", value_error_sum)
print("Sum of KeyError: ", key_error_sum)

Sum of NameError:  359
Sum of AssertionError:  1712
Sum of TypeError:  452
Sum of IndexError:  499
Sum of AttributeError:  151
Sum of UnboundLocalError:  33
Sum of ValueError:  62
Sum of KeyError:  6

In [13]:
import pandas as pd
# Load the CSV file into a pandas DataFrame
data = pd.read_csv("H22/errorH22morgen.csv", on_bad_lines='skip')

#Drop the first column
data = data.drop(data.columns[0], axis=1)

#Get unique data and their count
unique_values = data.stack().value_counts()

unique_values_df = unique_values.rename_axis('unique_value').reset_index(name='count')

# Display the grouped data as a table
unique_values_df.head(24)

                                         unique_value  count
0       AssertionError('False is not true : False')]]    554
1             IndexError('list index out of range')]]     50
2        AssertionError('False is not true : True')]]     47
3         NameError("name 'lenght' is not defined")]]     43
4             NameError("name 'np' is not defined")]]     41
5         TypeError("'int' object is not iterable")]]     38
6    ValueError('The truth value of an array with ...     34
7    IndexError('index 4 is out of bounds for axis...     33
8    IndexError('arrays used as indices must be of...     33
9        AssertionError('None is not true : False')]]     30
10        AssertionError('None is not true : True')]]     24
11   IndexError('index 5 is out of bounds for axis...     22
12                        AssertionError('0 != 11')]]     20
13                        AssertionError('3 != 11')]]     19
14             IndexError('pop index out of range')]]     19
15        NameError("name 'length' is not defined")]]     17
16   IndexError('index 4 is out of bounds for axis...     17
17              AssertionError('0 is not true : 3')]]     17
18           AssertionError('None is not true : 3')]]     16
19                        AssertionError('4 != 11')]]     14
20                     AssertionError('None != 11')]]     12
21                        AssertionError('7 != 11')]]     12
22                        AssertionError('6 != 11')]]     11
23   TypeError("'NoneType' object is not iterable")]]     11

In [14]:
# Load the CSV file into a pandas DataFrame
data = pd.read_csv("H22/errorH22morgen.csv", on_bad_lines='skip')

#Drop the first column
data = data.drop(data.columns[0], axis=1)

#Get unique data and their count
unique_values = data.stack().value_counts()

# Filter unique values containing "NameError"
name_error_values = [value for value in unique_values.index if "NameError" in value]
name_error_counts = unique_values[name_error_values]

# Sum the counts of the NameError values
name_error_sum = name_error_counts.sum()

# Filter unique values containing "AssertionError"
assertion_error_values = [value for value in unique_values.index if "AssertionError" in value]
assertion_error_counts = unique_values[assertion_error_values]

# Sum the counts of the AssertionError values
assertion_error_sum = assertion_error_counts.sum()

#Filter unique values containing "TypeError"
type_error_values = [value for value in unique_values.index if "TypeError" in value]
type_error_counts = unique_values[type_error_values]

# Sum the counts of the TypeError values
type_error_sum = type_error_counts.sum()

#Filter unique values containing "IndexError"
index_error_values = [value for value in unique_values.index if "IndexError" in value]
index_error_counts = unique_values[index_error_values]

# Sum the counts of the IndexError values
index_error_sum = index_error_counts.sum()

#Filter unique values containing "AttributeError"
attribute_error_values = [value for value in unique_values.index if "AttributeError" in value]
attribute_error_counts = unique_values[attribute_error_values]

# Sum the counts of the AttributeError values
attribute_error_sum = attribute_error_counts.sum()

#Filter unique values containing "UnboundLocalError"
unbound_local_error_values = [value for value in unique_values.index if "UnboundLocalError" in value]
unbound_local_error_counts = unique_values[unbound_local_error_values]

# Sum the counts of the UnboundLocalError values
unbound_local_error_sum = unbound_local_error_counts.sum()

#Filter unique values containing "ValueError"
value_error_values = [value for value in unique_values.index if "ValueError" in value]
value_error_counts = unique_values[value_error_values]

# Sum the counts of the ValueError values
value_error_sum = value_error_counts.sum()

#Filter unique values containing "KeyError"
key_error_values = [value for value in unique_values.index if "KeyError" in value]
key_error_counts = unique_values[key_error_values]

# Sum the counts of the KeyError values
key_error_sum = key_error_counts.sum()

# Display the grouped data as a table
print("Sum of NameError: ", name_error_sum)
print("Sum of AssertionError: ", assertion_error_sum)
print("Sum of TypeError: ", type_error_sum)
print("Sum of IndexError: ", index_error_sum)
print("Sum of AttributeError: ", attribute_error_sum)
print("Sum of UnboundLocalError: ", unbound_local_error_sum)
print("Sum of ValueError: ", value_error_sum)
print("Sum of KeyError: ", key_error_sum)

Sum of NameError:  240
Sum of AssertionError:  814
Sum of TypeError:  149
Sum of IndexError:  181
Sum of AttributeError:  41
Sum of UnboundLocalError:  31
Sum of ValueError:  46
Sum of KeyError:  0

In [15]:
import pandas as pd
# Load the CSV file into a pandas DataFrame
data = pd.read_csv("H22Kveld/errorH22kveld.csv", on_bad_lines='skip')

#Drop the first column
data = data.drop(data.columns[0], axis=1)

#Get unique data and their count
unique_values = data.stack().value_counts()

unique_values_df = unique_values.rename_axis('unique_value').reset_index(name='count')

# Display the grouped data as a table
unique_values_df.head(24)

                                         unique_value  count
0    IndexError('arrays used as indices must be of...     11
1                         AssertionError('0 != 15')]]     10
2             IndexError('list index out of range')]]      9
3    TypeError('only integer scalar arrays can be ...      7
4    ValueError('The truth value of an array with ...      6
5           AssertionError('None is not true : M3')]]      6
6    TypeError("'int' object is not subscriptable")]]      6
7         TypeError("'int' object is not iterable")]]      6
8    IndexError('index 4 is out of bounds for axis...      5
9             NameError("name 'M3' is not defined")]]      4
10           AssertionError('0 is not true : 38.2')]]      4
11   TypeError('only size-1 arrays can be converte...      4
12   IndexError('index 4 is out of bounds for axis...      4
13   TypeError("object of type 'int' has no len()")]]      4
14             NameError("name 'i' is not defined")]]      4
15      TypeError("'tuple' object is not callable")]]      3
16          NameError("name 'true' is not defined")]]      3
17        AssertionError('None is not true : 38.2')]]      3
18                     AssertionError('None != 15')]]      3
19   AttributeError("'numpy.float64' object has no...      2
20   UnboundLocalError("local variable 'sum' refer...      2
21             TypeError("unhashable type: 'list'")]]      2
22                                   TimeoutError()]]      2
23                        AssertionError('8 != 15')]]      2

In [16]:
# Load the CSV file into a pandas DataFrame
data = pd.read_csv("H22Kveld/errorH22kveld.csv", on_bad_lines='skip')

#Drop the first column
data = data.drop(data.columns[0], axis=1)

#Get unique data and their count
unique_values = data.stack().value_counts()

# Filter unique values containing "NameError"
name_error_values = [value for value in unique_values.index if "NameError" in value]
name_error_counts = unique_values[name_error_values]

# Sum the counts of the NameError values
name_error_sum = name_error_counts.sum()

# Filter unique values containing "AssertionError"
assertion_error_values = [value for value in unique_values.index if "AssertionError" in value]
assertion_error_counts = unique_values[assertion_error_values]

# Sum the counts of the AssertionError values
assertion_error_sum = assertion_error_counts.sum()

#Filter unique values containing "TypeError"
type_error_values = [value for value in unique_values.index if "TypeError" in value]
type_error_counts = unique_values[type_error_values]

# Sum the counts of the TypeError values
type_error_sum = type_error_counts.sum()

#Filter unique values containing "IndexError"
index_error_values = [value for value in unique_values.index if "IndexError" in value]
index_error_counts = unique_values[index_error_values]

# Sum the counts of the IndexError values
index_error_sum = index_error_counts.sum()

#Filter unique values containing "AttributeError"
attribute_error_values = [value for value in unique_values.index if "AttributeError" in value]
attribute_error_counts = unique_values[attribute_error_values]

# Sum the counts of the AttributeError values
attribute_error_sum = attribute_error_counts.sum()

#Filter unique values containing "UnboundLocalError"
unbound_local_error_values = [value for value in unique_values.index if "UnboundLocalError" in value]
unbound_local_error_counts = unique_values[unbound_local_error_values]

# Sum the counts of the UnboundLocalError values
unbound_local_error_sum = unbound_local_error_counts.sum()

#Filter unique values containing "ValueError"
value_error_values = [value for value in unique_values.index if "ValueError" in value]
value_error_counts = unique_values[value_error_values]

# Sum the counts of the ValueError values
value_error_sum = value_error_counts.sum()

#Filter unique values containing "KeyError"
key_error_values = [value for value in unique_values.index if "KeyError" in value]
key_error_counts = unique_values[key_error_values]

# Sum the counts of the KeyError values
key_error_sum = key_error_counts.sum()

# Display the grouped data as a table
print("Sum of NameError: ", name_error_sum)
print("Sum of AssertionError: ", assertion_error_sum)
print("Sum of TypeError: ", type_error_sum)
print("Sum of IndexError: ", index_error_sum)
print("Sum of AttributeError: ", attribute_error_sum)
print("Sum of UnboundLocalError: ", unbound_local_error_sum)
print("Sum of ValueError: ", value_error_sum)
print("Sum of KeyError: ", key_error_sum)

Sum of NameError:  38
Sum of AssertionError:  36
Sum of TypeError:  44
Sum of IndexError:  31
Sum of AttributeError:  10
Sum of UnboundLocalError:  8
Sum of ValueError:  7
Sum of KeyError:  0

In [17]:
# Load csv file into a pandas DataFrame
data = pd.read_csv("H21/errorH21.csv", on_bad_lines='skip')

#Group the data into values that contain "oppgave2a"
oppgave2a = data.stack().value_counts().filter(like='oppgave2a', axis=0)

#Group the data into values that contain "oppgave2b"
oppgave2b = data.stack().value_counts().filter(like='oppgave2b', axis=0)

#Group the data into values that contain "oppgave2c"
oppgave2c = data.stack().value_counts().filter(like='oppgave2c', axis=0)

#Group the data into values that contain "oppgave2g"
oppgave2g = data.stack().value_counts().filter(like='oppgave2g', axis=0)

#Group the data into values that contain "oppgave2h"
oppgave2h = data.stack().value_counts().filter(like='oppgave2h', axis=0)

#Group the data into values that contain "oppgave2i"
oppgave2i = data.stack().value_counts().filter(like='oppgave2i', axis=0)

#Group the data into values that contain "oppgave3_1"
oppgave3_1 = data.stack().value_counts().filter(like='oppgave3_1', axis=0)

#Group the data into values that contain "oppgave3_2"
oppgave3_2 = data.stack().value_counts().filter(like='oppgave3_2', axis=0)

#Group the data into values that contain "oppgave3_3"
oppgave3_3 = data.stack().value_counts().filter(like='oppgave3_3', axis=0)

#Group the data into values that contain "oppgave3_4"
oppgave3_4 = data.stack().value_counts().filter(like='oppgave3_4', axis=0)

#Group the data into values that contain "oppgave3_5"
oppgave3_5 = data.stack().value_counts().filter(like='oppgave3_5', axis=0)

#Group the data into values that contain "oppgave3_6"
oppgave3_6 = data.stack().value_counts().filter(like='oppgave3_6', axis=0)

#Print the counts of the grouped data
print("Oppgave 2a: ", oppgave2a.sum())
print("Oppgave 2b: ", oppgave2b.sum())
print("Oppgave 2c: ", oppgave2c.sum())
print("Oppgave 2g: ", oppgave2g.sum())
print("Oppgave 2h: ", oppgave2h.sum())
print("Oppgave 2i: ", oppgave2i.sum())
print("Oppgave 3.1: ", oppgave3_1.sum())
print("Oppgave 3.2: ", oppgave3_2.sum())
print("Oppgave 3.3: ", oppgave3_3.sum())
print("Oppgave 3.4: ", oppgave3_4.sum())
print("Oppgave 3.5: ", oppgave3_5.sum())

Oppgave 2a:  269
Oppgave 2b:  131
Oppgave 2c:  639
Oppgave 2g:  310
Oppgave 2h:  637
Oppgave 2i:  514
Oppgave 3.1:  774
Oppgave 3.2:  15
Oppgave 3.3:  0
Oppgave 3.4:  0
Oppgave 3.5:  0

In [18]:
# Load csv file into a pandas DataFrame
data = pd.read_csv("H22/errorH22morgen.csv", on_bad_lines='skip')

#Group the data into values that contain "oppgave1"
oppgave1 = data.stack().value_counts().filter(like='oppgave1', axis=0)

#Group the data into values that contain "oppgave2"
oppgave2 = data.stack().value_counts().filter(like='oppgave2', axis=0)

#Group the data into values that contain "oppgave3"
oppgave3 = data.stack().value_counts().filter(like='oppgave3', axis=0)

#Print the counts of the grouped data
print("Oppgave 1: ", oppgave1.sum())
print("Oppgave 2: ", oppgave2.sum())
print("Oppgave 3: ", oppgave3.sum())

Oppgave 1:  372
Oppgave 2:  782
Oppgave 3:  353

In [19]:
# Load csv file into a pandas DataFrame
data = pd.read_csv("H22Kveld/errorH22kveld.csv", on_bad_lines='skip')

#Group the data into values that contain "oppgave1"
oppgave1 = data.stack().value_counts().filter(like='oppgave1', axis=0)

#Group the data into values that contain "oppgave2"
oppgave2 = data.stack().value_counts().filter(like='oppgave2', axis=0)

#Group the data into values that contain "oppgave3"
oppgave3 = data.stack().value_counts().filter(like='oppgave3', axis=0)

#Print the counts of the grouped data
print("Oppgave 1: ", oppgave1.sum())
print("Oppgave 2: ", oppgave2.sum())
print("Oppgave 3: ", oppgave3.sum())

Oppgave 1:  51
Oppgave 2:  29
Oppgave 3:  96